package UC.LoadBalancer;

import java.awt.Color;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import static java.lang.Integer.parseInt;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingWorker;


public class LoadBalancer extends javax.swing.JFrame {
    
              
    private int numberOfClients = 0;
    private int numberOfServers = 0;
    private int serverPort;
    private int serverPortServer;
    private int serverPortMonitor;
    private Socket serverSocketServer;
    private Socket serverSocketClient;
    private Socket serverSocketMonitor;
    HashMap<Integer, Socket> allServerSocketsConnected = new HashMap<Integer, Socket>();
    HashMap<Integer, Socket> allClientsSocketsConnected = new HashMap<Integer, Socket>();  
    
    public LoadBalancer() throws IOException {
        initComponents();
        STATUSLabel.setVisible(false);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PORTTextField = new javax.swing.JTextField();
        STATUSLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SERVERPORTTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        SERVERSTEXTAREA = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        REQUESTSTEXTAREA = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        CLIENTSTEXTAREA = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        MONITORPORTTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("LoadBalancer");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Client Port:");

        PORTTextField.setText("7777");

        STATUSLabel.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        STATUSLabel.setForeground(new java.awt.Color(0, 100, 0));
        STATUSLabel.setText("Online");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Server Port:");

        SERVERPORTTextField.setText("8888");
        SERVERPORTTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SERVERPORTTextFieldActionPerformed(evt);
            }
        });

        SERVERSTEXTAREA.setColumns(20);
        SERVERSTEXTAREA.setRows(5);
        jScrollPane2.setViewportView(SERVERSTEXTAREA);

        REQUESTSTEXTAREA.setColumns(20);
        REQUESTSTEXTAREA.setRows(5);
        jScrollPane3.setViewportView(REQUESTSTEXTAREA);

        CLIENTSTEXTAREA.setColumns(20);
        CLIENTSTEXTAREA.setRows(5);
        jScrollPane4.setViewportView(CLIENTSTEXTAREA);

        jLabel4.setText("Connected Servers:");

        jLabel5.setText("Connected Clients:");

        jLabel6.setText("All Requests:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Monitor Port:");

        MONITORPORTTextField.setText("6666");
        MONITORPORTTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MONITORPORTTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MONITORPORTTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SERVERPORTTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(STATUSLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(PORTTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(0, 553, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PORTTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1)
                                    .addComponent(STATUSLabel)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(SERVERPORTTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(MONITORPORTTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)))
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

          if(serverSocketClient != null)
          {
              return;
          }
          
         try {
            serverPort = parseInt(PORTTextField.getText());   
            serverPortServer = parseInt(SERVERPORTTextField.getText());
            serverPortMonitor = parseInt(MONITORPORTTextField.getText());
          } catch (NumberFormatException ex) {
            Logger.getLogger(LoadBalancer.class.getName()).log(Level.SEVERE, null, ex);
            STATUSLabel.setForeground(Color.red);
            STATUSLabel.setText("Error Creating Server :/");
            STATUSLabel.setVisible(true); 
            return;
          }
        
          SwingWorker worker = new SwingWorker<Boolean, Integer>() {

          @Override
          protected Boolean doInBackground() throws Exception {
              {      
                ServerSocket serverSocket = null;
                try {
                    serverSocket = new ServerSocket(serverPortServer);  
                } catch (IOException ex) {
                    Logger.getLogger(LoadBalancer.class.getName()).log(Level.SEVERE, null, ex);
                    STATUSLabel.setForeground(Color.red);
                    STATUSLabel.setText("Error Creating Server :/");
                    STATUSLabel.setVisible(true); 
                    return false;
                }
                
                STATUSLabel.setForeground(new java.awt.Color(0, 100, 0));
                STATUSLabel.setText("ONLINE!");
                STATUSLabel.setVisible(true);                
                
                
                while(true)
                {
                    Socket s2 = null;
                    try {
                        s2 = serverSocket.accept();                       
                    } catch (IOException ex) {
                        Logger.getLogger(LoadBalancer.class.getName()).log(Level.SEVERE, null, ex);
                        System.exit(1);
                    }

                    InputStream inputStream2 = null;
                    try {
                        inputStream2 = s2.getInputStream();
                    } catch (IOException ex) {
                        Logger.getLogger(LoadBalancer.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    DataInputStream dataInputStream2 = new DataInputStream(inputStream2);
                    OutputStream outputStream = s2.getOutputStream();
                    DataOutputStream dataOutputStream = new DataOutputStream(outputStream);
                    try {  
                        String str = dataInputStream2.readUTF();                         
                        if("ImAliveServer".equals(str))
                        {
                            System.out.println("Sending new Server ID->"+numberOfServers);
                            dataOutputStream.writeUTF(String.valueOf(numberOfServers)+";Server");
                            dataOutputStream.flush();
                            serverSocketServer = s2;  
                            allServerSocketsConnected.put(numberOfServers,s2);
                            StringBuilder newTextArea = new StringBuilder();
                            for (Integer key : allServerSocketsConnected.keySet()) {
                                newTextArea.append("Server ID:")
                                   .append(key)
                                   .append(" = ")
                                   .append(allServerSocketsConnected.get(key))
                                   .append("\n");
                            }
                            SERVERSTEXTAREA.setText(newTextArea.toString());
                            numberOfServers++;
                        }
                        else if("ImAliveClient".equals(str) || "ImAliveMonitor".equals(str))
                        {
                            System.out.println("CLIENT TRIED TO ENTER PORT SERVER");
                            dataOutputStream.writeUTF("999;Server");
                            dataOutputStream.flush();                            
                        }
                        else
                        {
                            //Escolher melhor Servidor para enviar info
                            System.out.println("LOAD_BALANCER_RECEIVED->"+str);
                            String[] arrOfStr = str.split("|",-2);
                            System.out.println(allClientsSocketsConnected.get(parseInt(arrOfStr[0])).toString());
                            OutputStream outputStreamClient = allClientsSocketsConnected.get(parseInt(arrOfStr[0])).getOutputStream();
                            DataOutputStream dataOutputStreamClient = new DataOutputStream(outputStreamClient);
                            System.out.println(str+"?");
                            dataOutputStreamClient.writeUTF(str);
 
                        }       
                 

                    } catch (IOException ex) {
                        Logger.getLogger(LoadBalancer.class.getName()).log(Level.INFO, null, ex);
                        try {
                            s2.close();
                        } catch (IOException ex1) {
                            Logger.getLogger(LoadBalancer.class.getName()).log(Level.SEVERE, null, ex1);
                        }
                    }
                }  
            }
          }

          protected void process(Integer chunks) {
          }

          @Override
          protected void done() {
            System.out.println("Done");
          }
        };
        worker.execute();
        
        SwingWorker workerServer = new SwingWorker<Boolean, Integer>() {

          @Override
          protected Boolean doInBackground() throws Exception {
              {      
                ServerSocket serverSocket = null;
                try {
                    serverSocket = new ServerSocket(serverPort);       
                } catch (IOException ex) {
                    Logger.getLogger(LoadBalancer.class.getName()).log(Level.SEVERE, null, ex);
                    STATUSLabel.setForeground(Color.red);
                    STATUSLabel.setText("Error Creating Server :/");
                    STATUSLabel.setVisible(true); 
                    return false;
                }
                
                STATUSLabel.setForeground(new java.awt.Color(0, 100, 0));
                STATUSLabel.setText("ONLINE!");
                STATUSLabel.setVisible(true);                
                
                
                while(true)
                {
                    Socket s2 = null;
                    try {
                        s2 = serverSocket.accept(); 
                        serverSocketClient = s2;                        
                    } catch (IOException ex) {
                        Logger.getLogger(LoadBalancer.class.getName()).log(Level.SEVERE, null, ex);
                        System.exit(1);
                    }

                    InputStream inputStream2 = null;
                    try {
                        inputStream2 = s2.getInputStream();
                    } catch (IOException ex) {
                        Logger.getLogger(LoadBalancer.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    DataInputStream dataInputStream2 = new DataInputStream(inputStream2);
                    OutputStream outputStream = s2.getOutputStream();
                    DataOutputStream dataOutputStream = new DataOutputStream(outputStream);
                    try {  
                        String str = dataInputStream2.readUTF();               
                        if("ImAliveClient".equals(str))
                        {
                            System.out.println("Sending new Client ID->"+numberOfClients);
                            dataOutputStream.writeUTF(String.valueOf(numberOfClients)+";Client");  
                            allClientsSocketsConnected.put(numberOfClients,s2); 
                            StringBuilder newTextArea = new StringBuilder();
                            for (Integer key : allClientsSocketsConnected.keySet()) {
                                newTextArea.append("Client ID:")
                                   .append(key)
                                   .append(" = ")
                                   .append(allClientsSocketsConnected.get(key))
                                   .append("\n");
                            }
                            CLIENTSTEXTAREA.setText(newTextArea.toString());
                            numberOfClients++;
                        }
                        else if("ImAliveServer".equals(str) || "ImAliveMonitor".equals(str))
                        {
                            System.out.println("SERVER TRIED TO ENTER CLIENT");
                            dataOutputStream.writeUTF("999;Client");
                            dataOutputStream.flush();                            
                        }                        
                        else
                        {
                            //Escolher melhor Servidor para enviar info
                            System.out.println("else- "+str);
                            LoadBalancerRequest loadBalancerRequest = new LoadBalancerRequest(str,serverSocketServer,serverSocketClient); 
                            loadBalancerRequest.run();
                           
                        }

                    } catch (IOException ex) {
                        Logger.getLogger(LoadBalancer.class.getName()).log(Level.INFO, null, ex);
                        try {
                            s2.close();
                        } catch (IOException ex1) {
                            Logger.getLogger(LoadBalancer.class.getName()).log(Level.SEVERE, null, ex1);
                        }
                    }
                }  
            }
          }

          protected void process(Integer chunks) {
          }

          @Override
          protected void done() {
            System.out.println("Done");
          }
        };
        workerServer.execute();
        
        
        SwingWorker workerServer3 = new SwingWorker<Boolean, Integer>() {

          @Override
          protected Boolean doInBackground() throws Exception {
              {      
                ServerSocket serverSocket = null;
                try {
                    serverSocket = new ServerSocket(serverPortMonitor);       
                } catch (IOException ex) {
                    Logger.getLogger(LoadBalancer.class.getName()).log(Level.SEVERE, null, ex);
                    STATUSLabel.setForeground(Color.red);
                    STATUSLabel.setText("Error Creating Server :/");
                    STATUSLabel.setVisible(true); 
                    return false;
                }
                
                STATUSLabel.setForeground(new java.awt.Color(0, 100, 0));
                STATUSLabel.setText("ONLINE!");
                STATUSLabel.setVisible(true);                
                
                
                while(true)
                {
                    Socket s2 = null;
                    try {
                        s2 = serverSocket.accept(); 
                        serverSocketMonitor = s2;                        
                    } catch (IOException ex) {
                        Logger.getLogger(LoadBalancer.class.getName()).log(Level.SEVERE, null, ex);
                        System.exit(1);
                    }

                    InputStream inputStream2 = null;
                    try {
                        inputStream2 = s2.getInputStream();
                    } catch (IOException ex) {
                        Logger.getLogger(LoadBalancer.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    DataInputStream dataInputStream2 = new DataInputStream(inputStream2);
                    OutputStream outputStream = s2.getOutputStream();
                    DataOutputStream dataOutputStream = new DataOutputStream(outputStream);
                    try {  
                        String str = dataInputStream2.readUTF();               
                        if("ImAliveMonitor".equals(str))
                        {
                            System.out.println("Sending new Monitor ID->"+999);
                            dataOutputStream.writeUTF("999;Monitor");  
                        }
                        else if("ImAliveServer".equals(str) || "ImAliveClient".equals(str))
                        {
                            System.out.println("SERVER TRIED TO ENTER CLIENT");
                            dataOutputStream.writeUTF("999;Client");
                            dataOutputStream.flush();                            
                        }                        
                        else
                        {
                            //Info do Monitor
                            System.out.println("else- "+str);
                        }

                    } catch (IOException ex) {
                        Logger.getLogger(LoadBalancer.class.getName()).log(Level.INFO, null, ex);
                        try {
                            s2.close();
                        } catch (IOException ex1) {
                            Logger.getLogger(LoadBalancer.class.getName()).log(Level.SEVERE, null, ex1);
                        }
                    }
                }  
            }
          }

          protected void process(Integer chunks) {
          }

          @Override
          protected void done() {
            System.out.println("Done");
          }
        };
        workerServer3.execute();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SERVERPORTTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SERVERPORTTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SERVERPORTTextFieldActionPerformed

    private void MONITORPORTTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MONITORPORTTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MONITORPORTTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadBalancer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadBalancer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadBalancer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadBalancer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new LoadBalancer().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(LoadBalancer.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea CLIENTSTEXTAREA;
    private javax.swing.JTextField MONITORPORTTextField;
    private javax.swing.JTextField PORTTextField;
    private javax.swing.JTextArea REQUESTSTEXTAREA;
    private javax.swing.JTextField SERVERPORTTextField;
    private javax.swing.JTextArea SERVERSTEXTAREA;
    private javax.swing.JLabel STATUSLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
